"""empty message

Revision ID: 4e3c3581d41c
Revises: 
Create Date: 2018-07-11 12:16:35.373217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3c3581d41c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WEB_URL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WEB_URL')
    # ### end Alembic commands ###
